### PR TITLE
Routes refactoring + Auth Routes

### LINKED ISSUE #4: Define User signup / login routes

### PR DESCRIPTION
**Pull request by hpereira98**
Refactored the API routes to use @api_view instead of ModelViewSet. This will allow us to have more development flexibility and easier customization.

Added routes that allow signup and login. Authentication is done with DRF Token Authentication.

Future work: implement getters for personal data and for other user data, for loan requests and investments. add password recovery methods. send email on signup and password recovery. add user methods like update profile data.

### CODE REVIEW

**Comment by hpereira98** [comment]
Added the basic setup for the API documentation
Fixed the Create Investment route
Added getters for Investments (personal and by ID) and Loan Requests (personal, by ID, all active and investments of each)

**Review by ricardomilhazes — APPROVED** [review]
Everything looks good. Maybe take this into consideration:
- Create a method on signup to check if email exists
- I would say that we should only pass loan_request info if it's validated

Great job btw 👍

**Comment by hpereira98** [comment]
> Everything looks good. Maybe take this into consideration:
> 
> * Create a method on signup to check if email exists
> * I would say that we should only pass loan_request info if it's validated
> 
> Great job btw 👍

Sure, I've created an Issue for that method! #16 
Regarding the Loan Request info, let's see what the others say, but we could also check with the frontend team to see what they actually need

**Comment by ricardofsc10** [comment]
Looks nice. APIView are indeed better in our project as we will need to customize some routes. Great that you confirmed that and changed the views style.

Regarding what @ricardomilhazes pointed out about Loan Request info I agree with him however we SHOULD talk with the frontend team so I then can tell us what they really need.

Let's move forward.

**Review by ricardofsc10 — APPROVED** [review]

**Pull request merged**
