### PR TITLE
Fix typo in Token Contract Address

### PR DESCRIPTION
**Pull request by joaop21**

### CODE REVIEW

**Comment by albertofaria** [comment]
While we're at it, how about just replacing the two lines with `loan_dict["token_address"] = str(fetched_loan.token_contract_address)`?

**Comment by albertofaria** [comment]
This may be a bit of a nitpick, but `fetched_loan.get_state()` should be called just once to ensure that we return a consistent snapshot of the loan.

**Comment by joaop21** [comment]
> This may be a bit of a nitpick, but `fetched_loan.get_state()` should be called just once to ensure that we return a consistent snapshot of the loan.

I was just fixing a typo in a word, but I can fix that too

**Comment by albertofaria** [comment]
> > This may be a bit of a nitpick, but `fetched_loan.get_state()` should be called just once to ensure that we return a consistent snapshot of the loan.
> 
> I was just fixing a typo in a word, but I can fix that too

My bad, thanks for the fix.

**Review by albertofaria — APPROVED** [review]

**Review by hpereira98 — APPROVED** [review]

**Pull request merged**
